Rectified some Synatx Errors in various py files
OpenChemistry/molequeue pull request #34
Opened 2023-09-09 12:53 UTC by adityaomar3

There were few synatx errors in py file mostly due to change in version of python. Rectified in this commit

2023-09-09 14:00 UTC, cclauss requested changes

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/sendRpcKill.py
> +    print ("Connecting to socket: %s"%socketname)
Correct.  `print()` is a function in Python 3 but write it like other functions as `print()`, not `print ()`...
```suggestion
    print("Connecting to socket: %s"%socketname)
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/sendRpcKill.py
> +    print (ex)
```suggestion
    print(ex)
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/sendRpcKill.py
> +    print ("Exiting with code: %d"%test_result)
```suggestion
    print("Exiting with code: %d" % test_result)
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/submitJob.py
> +    print ("Client %s connecting to socket: %s"%(clientId, socketname))
```suggestion
    print("Client %s connecting to socket: %s" % (clientId, socketname))
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/submitJob.py
> +            print ("Job %d finished! (Client %s)"%(moleQueueId, clientId))
```suggestion
            print("Job %d finished! (Client %s)" % (moleQueueId, clientId))
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/submitJob.py
> +      print ("Unexpected notification:", msg, ex)
```suggestion
      print("Unexpected notification:", msg, ex)
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/submitJob.py
> +      print ("Submitted job %d (Client %s)"%(molequeue_id, clientId))
```suggestion
      print("Submitted job %d (Client %s)" % (molequeue_id, clientId))
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/submitJob.py
> +        (clientId, timeout, len(molequeue_ids) - len(molequeue_ids_done)))
```suggestion
      print("Client %s waiting to finish (timeout=%d unmatchedIDs=%d)" %
        (clientId, timeout, len(molequeue_ids) - len(molequeue_ids_done)))
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/submitJob.py
> +    print (ex)
```suggestion
    print(ex)
```

2023-09-09 14:00 UTC, cclauss commented on molequeue/app/testing/scripts/submitJob.py
> +    print ("Exiting with code: %d (client %s)"%(test_result, clientId))
```suggestion
    print("Exiting with code: %d (client %s)" % (test_result, clientId))
```

2023-09-09 14:00 UTC, cclauss commented on python/test/clienttest.py
> +    print ("MoleQueue ID: ", molequeue_id)
```suggestion
    print("MoleQueue ID: ", molequeue_id)
```

2023-09-09 14:00 UTC, cclauss commented on python/test/clienttest.py
> +      print (q.name, ", ", q.programs)
```suggestion
      print(q.name, ", ", q.programs)
```

2023-09-09 16:14 UTC, adityaomar3 commented on molequeue/app/testing/scripts/sendRpcKill.py
> +    print ("Connecting to socket: %s"%socketname)
> Correct. `print()` is a function in Python 3 but write it like other functions as `print()`, not `print ()`...

Yeah sure, that may have happened due to auto formatting of code

2023-09-09 16:16 UTC, cclauss commented on molequeue/app/testing/scripts/sendRpcKill.py
> +    print ("Connecting to socket: %s"%socketname)
I see no such automation...  https://github.com/OpenChemistry/molequeue/actions

2023-09-09 16:20 UTC, adityaomar3 commented
@cclauss successfully removed the additional spaces, please review it again

2023-09-09 16:54 UTC, adityaomar3 commented on molequeue/app/testing/scripts/sendRpcKill.py
> +    print ("Connecting to socket: %s"%socketname)
> I see no such automation... https://github.com/OpenChemistry/molequeue/actions

Sorry I meant by VS code in my pc.

2023-09-09 17:53 UTC, cclauss commented on molequeue/app/testing/scripts/submitJob.py
> +      print("Client %s waiting to finish (timeout=%d unmatchedIDs=%d)"%\
```suggestion
      print("Client %s waiting to finish (timeout=%d unmatchedIDs=%d)"%
```

2023-09-09 18:00 UTC, adityaomar3 commented on molequeue/app/testing/scripts/submitJob.py
> +      print("Client %s waiting to finish (timeout=%d unmatchedIDs=%d)"%\
> 

Done

2023-09-09 20:35 UTC, cclauss approved these changes

2023-09-09 20:39 UTC, adityaomar3 commented
@cclauss can we now merge this to master?

2023-10-02 03:04 UTC, ghutchis commented
@adityaomar3 - it's not quite dead, but it's been accumulating rust.

I'll take a look at this in the next day or two.

2024-10-24 19:13 UTC, merged